# config.toml - Box configuration file

[[boxes]]
    box = "box-A"
    children = [ "box-AB", "box-BB" ]
[[boxes]]
    box = "box-AB"
    children = [ "box-ABA", "box-ABB" ]
[[boxes]]
    box = "box-ABA"
[[boxes]]
    box = "box-ABB"
[[boxes]]
    box = "box-BB"