# config.toml - Box configuration file

[[boxes]]
  box = "box1"
  children = [ "box2", "box5" ]
[[boxes]]
  box = "box2"
  children = [ "box3", "box4" ]
[[boxes]]
  box = "box3"
[[boxes]]
  box = "box4"
[[boxes]]
  box = "box5"