<?xml version="1.0" encoding="UTF-8"?>
<nestconfig>
  <box id="box1">
    <child>box2</child>
    <child>box3</child>
    <child>box4</child>
  </box>
  <box id="box2">
    <child>box5</child>
    <child>box6</child>
    <child>box7</child>
  </box>
  <box id="box3">
    <child>box8</child>
    <child>box9</child>
    <child>box10</child>
  </box>
  <box id="box4">
    <child>box11</child>
    <child>box12</child>
    <child>box13</child>
  </box>
  <box id="box5"/>
  <box id="box6"/>
  <box id="box7"/>
  <box id="box8"/>
  <box id="box9"/>
  <box id="box10"/>
  <box id="box11"/>
  <box id="box12"/>
  <box id="box13"/>
</nestconfig>
