# example2.toml - Box configuration file

[[boxes]]
  box = "box1"
  children = [ "box2", "box3", "box4", "box5" ]
[[boxes]]
  box = "box2"
  children = [ "box6", "box7", "box8" ]
[[boxes]]
  box = "box3"
[[boxes]]
  box = "box4"
[[boxes]]
  box = "box5"
  children = [ "box11", "box12" ]
[[boxes]]
  box = "box6"
  children = [ "box9", "box10" ]
[[boxes]]
  box = "box7"
[[boxes]]
  box = "box8"
[[boxes]]
  box = "box9"
[[boxes]]
  box = "box10"
[[boxes]]
  box = "box11"
[[boxes]]
  box = "box12"